### ISSUE TITLE
test_segmentation.cpp  Failed to parse NetParameter file

### ISSUE THREAD

**Issue by xunkaixin** [TimoSaemann/caffe-segnet-cudnn5#10]
### Issue summary
Hello
I tried to run the code test_segmentation.cpp  CPU_ONLY . I get the error

./test_segmentation.bin  Example_Models/bayesian_segnet_camvid.prototxt  weights/bayesian_segnet_camvid.caffemodel CamVid/test/Seq05VD_f01230.png  Scripts/camvid12.png

[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 450:24: Message type "caffe.DropoutParameter" has no field named "sample_weights_test".
F0411 15:32:52.484048 26838 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: Example_Models/bayesian_segnet_camvid.prototxt

Any suggestions on getting this working?

   thank you!

Operating system: ubuntu 16.04

**Comment by TimoSaemann** [comment]
Hi,
I have added _sample_weights_test_ to caffe-segnet-cudnn5.

**Comment by xunkaixin** [comment]
thank you！ it works

**Comment by zhuyizi** [comment]
Hello,did you solved this problem?Can you tell about what should be done to solve it?

**Comment by zhuyizi** [comment]
Hello,did you solve this problem?Can you tell me about what should be done to solve it?
