### ISSUE TITLE
accuracy decreases with weights finetuned on cityscapes

### ISSUE THREAD

**Issue by Jennifer-Mack** [TimoSaemann/caffe-segnet-cudnn5#11]
Hy @TimoSaemann,
I am very new to SegNet as well as Caffe. I tried to use the weights of the webdemo of SegNet as well as the weights that you finetuned on Cityscapes.
My results looked like this:
![segnet](https://cloud.githubusercontent.com/assets/27426292/25006569/b98de332-205d-11e7-8c10-ba61b1d1ac32.png) Webdemo
![segnet citiyscapes](https://cloud.githubusercontent.com/assets/27426292/25006574/bcf1d68c-205d-11e7-8f59-4c0ef4f12b09.png) finetuned on Cityscapes

Do you know why in this test the classes are less distinct with the weights finetuned on Cityscapes?
I expected it to be the other way around.
Did I get some settings wrong or does the input video have an impact or maybe does it work better with videos from inside a city? I used one from a highway. 

I used @alexgkendall 's caffe-segnet and followed the tutorial. As a model filed I used the segnet_model_driving_webdemo.prototxt and just changed the weights.

Operating system: Ubuntu 14.04
Compiler: gcc 4.8.4
CPU_ONLY
BLAS: ATLAS
Python: 2.7

**Comment by TimoSaemann** [comment]
Hi @Jennifer-Mack 
I don't know what happend in your case, but as you pointed out, the weights finetuned on Cityscapes should lead to better results as the webdemo model.
