### ISSUE TITLE
Using Validation Dataset as a part of training Segnet

### ISSUE THREAD

**Issue by Viswa14** [TimoSaemann/caffe-segnet-cudnn5#15]
Hi,

I wish to use val.txt file and validate my data during training process. If I have to add validation during training process, how do I handle Batch Normalization ? with respect to that what kind of changes are needed in the train.prototxt ?

**Comment by TimoSaemann** [comment]
Hi, 

you don't need any changes for the batch normalization layers. 
You just need to change the first two lines of your solver file:
```
train_net: "/home/user/segnet_train.prototxt" 
test_net: "/home/user/segnet_val.prototxt"
```
