### ISSUE TITLE
A problem when make runtest

### ISSUE THREAD

**Issue by jamiesoung** [TimoSaemann/caffe-segnet-cudnn5#4]
### Issue summary

[----------] 1 test from LayerFactoryTest/2, where TypeParam = caffe::GPUDevice<float>
[ RUN      ] LayerFactoryTest/2.TestCreateLayer
*** Aborted at 1483801360 (unix time) try "date -d @1483801360" if you are using GNU date ***
PC: @     0x7f3458fca962 (unknown)
*** SIGSEGV (@0x118) received by PID 1777 (TID 0x7f346b689800) from PID 280; stack trace: ***
    @     0x7f3459321390 (unknown)
    @     0x7f3458fca962 (unknown)
    @     0x7f3459cd67a5 caffe::BasePrefetchingDataLayer<>::~BasePrefetchingDataLayer()
    @     0x7f3459d99e09 caffe::DataLayer<>::~DataLayer()
    @           0x4ec5e8 caffe::LayerFactoryTest_TestCreateLayer_Test<>::TestBody()
    @           0x8f63d3 testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x8f01ea testing::Test::Run()
    @           0x8f0338 testing::TestInfo::Run()
    @           0x8f0415 testing::TestCase::Run()
    @           0x8f162f testing::internal::UnitTestImpl::RunAllTests()
    @           0x8f1943 testing::UnitTest::Run()
    @           0x46dacd main
    @     0x7f3458f67830 (unknown)
    @           0x475509 _start
Makefile:526: recipe for target 'runtest' failed
make: *** [runtest] Segmentation fault (core dumped)

### Steps to reproduce

make runtest -j16

### Your system configuration
Operating system:Ubuntu16.04
Compiler:GCC5.3
CUDA version (if applicable):8.0
CUDNN version (if applicable):v5.1
BLAS:atlas
Python or MATLAB version (for pycaffe and matcaffe respectively):Python2.7

**Comment by TimoSaemann** [comment]
I can not reproduce that error.
I tried it on 3 different machines and no error occurred:

    Ubuntu 14.04, CUDA 8.0, Titan X (Pascal), cuDNN v.4 /v.5 /v.5.1, compiled with cmake and make
    Ubuntu 14.04, CUDA 7.5, Titan X (Maxwell), cuDNN v.4 /v.5 /v.5.1, compiled with cmake and make
    Ubuntu 16, CUDA 8.0, GTX 980, cuDNN v.5.1, compiled with cmake

Did you compiled it with cmake or make? Did you change in your makefile.config something else then uncomment the cuDNN flag?
Can you test and train SegNet anyway or which errors do you encounter?

**Comment by nathanin** [comment]
Hello, 
I have now run into this error while building on an AWS g2x.large instance (ubuntu 16.04, CUDA 8, CUDNN 5.1). I was able to make and pass all tests on another ubuntu machine, also 16.04, but which has the K4000 GPU. Also, my OS X El Capitan laptop with the measly GeForce GT 650M was able to make and pass all tests. 

I have used `make` all the time. 

In `Makefile.config`, nothing has changed, except to uncomment cuDNN flag, and add usr/include/hdf5/serial to the `INCLUDE_DIRS`. 

Haven't gotten to train and test SegNet on the AWS instance yet. I will update if it's successful or not in ~12 hours.

**Comment by TimoSaemann** [comment]
Does the same error occurs, when you compile it with cmake? 
Do you have caffe (master branch) compiled on that machine and are you able to train with it successfully?

**Comment by nathanin** [comment]
@TimoSaemann Thank you for the reply. 
I have just tried with cmake and eventually got the exact same error in runtest. 

Master branch compiles and seems to train no problem. I used make to build it, and ran the MNIST example with no issues. 

Is any specific output or other info needed to debug this? I think it's odd this happens on this specific machine, and no others I, or you, have used.

**Comment by srinivasnisha** [comment]
It might be failing cause of the  presence of multiple GPUs in your system. Try 
export CUDA_VISIBLE_DEVICES=0
echo $CUDA_VISIBLE_DEVICES -> should show 0
and then run make runtest -j8

**Comment by hopkinskong** [comment]
`sudo apt-get install libtcmalloc-minimal4`

Adding it in LD_PRELOAD variable, then `make runtest` again:
`export LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4"`

You may need to add it in `~/.bashrc` too.
