### ISSUE TITLE
Comping with CUDA8 - CuDNN5

### ISSUE THREAD

**Issue by whatnick** [TimoSaemann/caffe-segnet-cudnn5#5]
Hi, I am getting this error while compiling. Is the port complete ?
`"int" is incompatible with parameter of type "cudnnNanPropagation_t"`

Using CMake to configure build:
```
-- CUDA detected: 8.0
-- Found cuDNN: ver. 5.0.5 found (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Added CUDA NVCC flags for: sm_52 sm_30
```

**Comment by TimoSaemann** [comment]
Actually this error occurs when the used cuDNN version is not supported, but the repository supports definitely cuDNN version 5. Are you sure you compiled caffe-segnet-cudnn5 ?

**Comment by whatnick** [comment]
Checked out this repo specifically for that reason. Will get my ML machine back in a couple of days and start fresh to try again.
